import { Inter } from '@next/font/google';
import StoreProvider from '../store/StoreProvider';
import './global.css';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang='en'>
        <body className={inter.className}>{children}</body>
      </html>
    </StoreProvider>
  );
}
